# Generated by Django 3.1 on 2020-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(default='', upload_to='', verbose_name='Зображення'),
        ),
    ]
