# Generated by Django 3.1 on 2020-08-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='goods',
            new_name='product',
        ),
    ]
