# Generated by Django 3.1 on 2020-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення'),
        ),
    ]
