# Generated by Django 3.1 on 2020-08-14 10:54

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number_tel',
            field=phone_field.models.PhoneField(max_length=13, verbose_name='Номер телефону'),
        ),
    ]
