# Generated by Django 3.1 on 2020-08-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва головного каталогу')),
            ],
            options={
                'verbose_name': 'Головний каталог',
                'verbose_name_plural': 'Головні каталоги',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва підкаталогу')),
                ('mainCatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MainCatalogRel', to='mainsite.maincatalog', verbose_name='Назва головного каталогу')),
            ],
            options={
                'verbose_name': 'Підкаталог',
                'verbose_name_plural': 'Підкаталоги',
            },
        ),
    ]
