# Generated by Django 3.1 on 2020-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='images',
            field=models.ManyToManyField(to='mainsite.PropertyImage'),
        ),
    ]
