# Generated by Django 3.1 on 2020-08-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image_caption',
            field=models.CharField(max_length=35),
        ),
    ]
