# Generated by Django 3.1 on 2020-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200818_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='Ціна'),
        ),
    ]
