# Generated by Django 3.1 on 2020-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
