# Generated by Django 3.1 on 2020-08-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200825_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
