# Generated by Django 3.1 on 2020-08-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Ціна')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Замовив(ла)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Замовлений товар',
                'verbose_name_plural': 'Замовлені товари',
            },
        ),
    ]
